# Generated by Django 4.2.10 on 2024-02-26 11:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('introduction', models.TextField(blank=True)),
                ('hero_cta', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use page's listing title.", required=False))]))], blank=True)),
                ('body', wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='components/streamfield/blocks/heading2_block.html')), ('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul', 'h3'], template='components/streamfield/blocks/paragraph_block.html'))]))])), ('cta', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', required=True)), ('link', wagtail.blocks.StreamBlock([('internal', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text="Leave blank to use page's listing title.", required=False))])), ('external', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock()), ('title', wagtail.blocks.CharBlock())]))])), ('description', wagtail.blocks.TextBlock(required=False))])), ('statistics', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', required=True)), ('sr_only_label', wagtail.blocks.BooleanBlock(help_text='If checked, the heading will be hidden from view and avaliable to screen-readers only.', label='Screen reader only label', required=False)), ('statistics', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('utils.Statistic'), max_num=3, min_num=3))]))])),
                ('featured_section_title', models.TextField(blank=True)),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
