# Generated by Django 4.2.10 on 2024-02-26 10:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessagesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_404', models.CharField(default='Page not found', max_length=255, verbose_name='Title')),
                ('body_404', wagtail.fields.RichTextField(default='<p>You may be trying to find a page that doesn&rsquo;t exist or has been moved.</p>', verbose_name='Text')),
                ('footer_newsletter_signup_title', models.CharField(default='Sign up for our newsletter', max_length=120)),
                ('footer_newsletter_signup_description', models.CharField(blank=True, max_length=255)),
                ('footer_newsletter_signup_link', models.URLField(blank=True, help_text='Link to the newsletter signup form. If left blank, the signup CTA will not be displayed.', null=True)),
                ('placeholder_image', models.ForeignKey(help_text='Choose the image you wish to be displayed as a placeholder image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'system messages',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(blank=True, help_text='Your Twitter username without the @, e.g. katyperry', max_length=255)),
                ('linkedin_handle', models.CharField(blank=True, help_text='Your Linkedin handle, e.g. katyperry.', max_length=255)),
                ('facebook_app_id', models.CharField(blank=True, help_text='Your Facebook app ID.', max_length=255)),
                ('instagram_handle', models.CharField(blank=True, help_text='Your Instagram username, e.g. katyperry', max_length=255)),
                ('tiktok_handle', models.CharField(blank=True, help_text='Your TikTok username, e.g. katyperry', max_length=255)),
                ('default_sharing_text', models.CharField(blank=True, help_text='Default sharing text to use if social text has not been set on a page.', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageRelatedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_related_pages', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
        ),
    ]
